load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "low_level_io_benchmark",
    srcs = ["low_level_io_benchmark.cc"],
    deps = [
        "@com_google_benchmark//:benchmark",
        "@glog",
    ],
)