filegroup(
    name = "test_data",
    srcs = glob([
        "**/*.pdbqt",
        "**/*.pdbqt.gz",
    ]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "pdbqt",
    srcs = glob(["**/*.pdbqt"]),
    visibility = ["//visibility:public"],
)
